### ISSUE TITLE
JellyCon login error on 10.7.0-RC1

### ISSUE THREAD

**Issue by ddurdle** [mcarlton00/jellycon#34] opened 2020-12-10 00:03 UTC
**Describe the bug**
Doesn't seem compatible with 10.7.0-RC1
**To Reproduce**
Click Change server, enter server details.  Click Change User.  Provide correct username and password.  Presented with Not able to connect:  Incorrect Username/Password

**Expected behavior**
Login

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Android, Debian, Windows]
 - Jellyfin Version: [e.g. 10.0.1]
 - Kodi Version: [e.g. 18.3]
 - Addon Version: [e.g. 0.1.1]

**Additional context**

**Comment by mcarlton00** [comment] 2020-12-10 03:22
Duplicate of #20, fixed by #33

**Closed by mcarlton00** 2020-12-10 03:22 UTC
Labels: bug
